name: fuk_ui_kit_sample
description: "A new Flutter project."
publish_to: "none"
version: 0.1.2

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  highlight: ^0.7.0
  http: ^1.2.1
  re_editor: ^0.3.0
  dart_style: ^2.3.6
  get: ^4.6.6
  fuk_ui_kit:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
